CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6 accelerate launch --multi_gpu train_with_lora.py \
  --pretrained_model_name_or_path=stabilityai/stable-diffusion-xl-base-1.0  \
  --pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix \
  --output_dir="dpo" \
  --mixed_precision="fp16" \
  --dataset_name=Jialuo21/Phys_data \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --gradient_checkpointing \
  --lora_rank=8 \
  --use_8bit_adam \
  --learning_rate=1e-7 \
  --scale_lr \
  --dpo_training \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=6000 \
  --checkpointing_steps=500 \
  --seed="0" \
  --run_validation --validation_steps=50 \
  --report_to="wandb"